name: CI

on:
  push:
    branches:
      - master

jobs:
  run-unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Get Lates Code
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1

    - name: Install composer dependencies
      run: | 
        composer install --no-scripts
        
    - name: Run Test
      run: |
        vendor/bin/phpunit tests/Unit/ExampleTest.php


# CD
# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set up PHP
#       uses: shivammathur/setup-php@v2
#       with:
#         php-version: '7.4'

#     - name: Install FTP client
#       run: sudo apt-get install -y lftp

#     - name: Deploy via FTP
#       env:
#         FTP_HOST: ${{ secrets.FTP_HOST }}
#         FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
#         FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
#       run: |
#         lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; set ssl:verify-certificate no; mirror -Rnev . /public_html --exclude-glob .github"
